### ISSUE TITLE
Realtime don't work with pusher. 

### ISSUE THREAD

**Issue by bm777** [dongido001/python-realtime-table#1]
Realtime don't work with pusher. After installing all requirement library. It don't work. only if I refresh the main page ([index.html](127.0.0.1:500))

**Comment by dongido001** [comment]
is there any console error?

**Comment by bm777** [comment]
No, I have resolved my problem.

The problem was at the level of parsing data from app.py function to HTML.

**Comment by dongido001** [comment]
Alright

**Comment by njay98** [comment]
I think I am having similar issues, please help.  I also run into issues when running app.py 
It mentions that I have a NoneType error but the field is certainly a string. I also have everything intalled correctly. Please advise 

![cap](https://user-images.githubusercontent.com/52171845/61547364-da4a1e80-aa10-11e9-9637-e542878edd9b.PNG)
![Capture](https://user-images.githubusercontent.com/52171845/61547365-da4a1e80-aa10-11e9-81f0-1bc3cb8a6562.PNG)
![Capture2](https://user-images.githubusercontent.com/52171845/61547366-da4a1e80-aa10-11e9-8a49-379346906829.PNG)
